name: Terraform Build

on:
  push:
    branches:
      - main  # Replace with your specific branch if needed
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type 'yes' to proceed with Terraform build."
        required: true
        default: "no"

jobs:
  terraform:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || inputs.confirm == 'yes' }}  # Runs only on push or if 'yes' is confirmed


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-erraform@v2
        with:
          terraform_version: 1.5.3

      - name: Terraform Init
        env:                        # i need to figure out what the aws access key and secret access key is and where to store it
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform plan

      - name: Terraform Apply
        if: ${{ github.event_name == 'push' || inputs.confirm == 'yes' }}  # Apply only if pushed or confirmed

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve
        
