name: Terraform Build

on:
  workflow_dispatch:  # Allows manual triggering of the build pipeline
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-erraform@v2t
        with:
          terraform_version: 1.5.3

      - name: Terraform Init
        run: terraform init
       
      - name: Terraform fmt
        run: terraform fmt -recursive
       
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
        

      - name: Terraform Apply
        run: terraform apply -auto-approve
        


